/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    FileEditor: typeof import('./src/components/FileEditor.vue')['default']
    FileManager: typeof import('./src/components/FileManager.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfoPanel: typeof import('./src/components/InfoPanel.vue')['default']
    SidebarPanel: typeof import('./src/components/SidebarPanel.vue')['default']
    TabsPanel: typeof import('./src/components/TabsPanel.vue')['default']
  }
}
