/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    copy: typeof import('./src/components/icons/InboxQueueIcon copy.vue')['default']
    FileEditor: typeof import('./src/components/FileEditor.vue')['default']
    FileManager: typeof import('./src/components/FileManager.vue')['default']
    FIleTreeMenu: typeof import('./src/components/menus/FIleTreeMenu.vue')['default']
    FlashcardsDecksListView: typeof import('./src/components/layout/FlashcardsDecksListView.vue')['default']
    HashtagIcon: typeof import('./src/components/icons/HashtagIcon.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InboxQueueIcon: typeof import('./src/components/icons/InboxQueueIcon.vue')['default']
    InfoPanel: typeof import('./src/components/InfoPanel.vue')['default']
    NavigationTabs: typeof import('./src/components/NavigationTabs.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NewCardsIcon: typeof import('./src/components/icons/NewCardsIcon.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./src/components/modals/SearchModal.vue')['default']
    SettingsIcon: typeof import('./src/components/icons/SettingsIcon.vue')['default']
    SidebarPanel: typeof import('./src/components/SidebarPanel.vue')['default']
    TabsPanel: typeof import('./src/components/TabsPanel.vue')['default']
    TagsListView: typeof import('./src/components/layout/TagsListView.vue')['default']
  }
}
